### ISSUE TITLE
No detect devices

### ISSUE THREAD

**Issue by hortigado** [pedrofraca/scrcpyui#11]
Hi great tool, but i have a problem. The tool no detect devices

![Image](https://github.com/user-attachments/assets/693080d7-628f-40c4-aee1-51649dc12fd0)

**Comment by pedrofraca** [comment]
Hey @hortigado, indeed I managed to reproduce the issue. Give me some time, to debug it, and I'll get back to you. Thanks for trying the tool.

**Comment by pedrofraca** [comment]
Issue should be solved, please update version.

**Comment by hortigado** [comment]
![Image](https://github.com/user-attachments/assets/22b02edc-03c9-4c9f-8fa2-3f31ea12fe1a)
Hello, Thanks I downloaded the new update but the problem persists.

**Comment by pedrofraca** [comment]
Ok, I'll continue checking it. Probably adb isn't found by the app. Can you quickly check on the console any message by the process scrcpyui. 

And, which mechanism did you used to update the version? just downloading the dmg?


Thanks

**Comment by hortigado** [comment]
Hi, yes i download the new .dmg

**Comment by pedrofraca** [comment]
Can you check in the console app for any messages from the scrcpy process? 

thanks

**Comment by ghost** [comment]
When I ran the new version, it didn't work, so I compiled it and ran it, but the path set in ~/.zshrc wasn't applied, so I couldn't run the external command.

I modified only the two parts below and ran it, and it worked well.
let _ = commandLine.execute(arguments:[ "-l", "-c", "source ~/.zshrc && scrcpy -s \(device)" ], readOutput: false)
let result = commandLine.execute(arguments:[ "-l", "-c", "source ~/.zshrc && adb devices" ], readOutput: true)

thanks

**Comment by pedrofraca** [comment]
thanks @nextuplab , if you're fine I can add the code or if you feel like, please create a PR.
